//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED
//FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED  FILE DELETED  FILE DELETED   FILE DELETED


// sap.ui.define([
//   // "sap/m/Text",                          //Step-1
//   // "sap/ui/core/mvc/XMLView"             //Step-4
//   "sap/ui/core/ComponentContainer"
//
// ], function (ComponentContainer) {
//   "use strict";
//
//   //Step-2
//   // aler('hello world')
//
//   // Step-3
//   // new Text({
//   //   text:"Hello World"
//   // }).placeAt('content');
//
//   //Step-4
//   // XMLView.create({
//   //   viewName: "walkthrough.view.app"
//   // }).then(function(oView){
//   //   oView.placeAt('content');
//   // });
//
//   //Step-9
//   new ComponentContainer({
// 		name: "walkthrough",
// 		settings : {
// 			id : "walkthrough"
// 		},
// 		async: true
// 	}).placeAt("content");
// });
